name: 'desafiofinal_lighthouse'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  desafiofinal_lighthouse:
    marts:
      facts:
        +materialized: table
      dimensions:
        +materialized: table
      aggregates:
        +materialized: table
    staging:
      +materialized: view

seeds:
  desafiofinal_lighthouse:
    sap_adventure_works:
      +schema: sap_adw
