version: 2

sources:
  - name: adventureworks
    description: Source schema 'sap_adw' containing AdventureWorks data
      used for staging and transformation.
    database: adventureworks
    schema: sap_adw
    tables:
      - name: address
        description: Street address information for customers, employees, and vendors.
        columns:
          - name: addressid
            description: Primary key for address records.
            tests:
              - unique
              - not_null

      - name: countryregion
        description: Lookup table containing the ISO standard codes for countries and regions.
        columns:
          - name: countryregioncode
            description: ISO standard code for countries and regions.
            tests:
              - unique
              - not_null

      - name: customer
        description: General customer information.
        columns:
          - name: customerid
            description: Primary key of the customer table
            tests:
              - unique
              - not_null

      - name: creditcard
        description: Customer credit card information.
        columns:
          - name: creditcardid
            description: Primary key for the credit card records.
            tests:
              - unique
              - not_null

      - name: person
        description: Human beings involved with AdventureWorks, employees, customer contacts, and vendor contacts.
        columns:
          - name: businessentityid
            description: Primary key for Person records.
            tests:
              - unique
              - not_null

      - name: product
        description: Products sold or used in the manufacturing of sold products.
        columns:
          - name: productid
            description: Primary key for the products table.
            tests:
              - unique
              - not_null

      - name: productcategory
        description: High-level product categorization.
        columns:
          - name: productcategoryid
            description: Primary key for the product category table.
            tests:
              - unique
              - not_null

      - name: productinventory
        description: Inventory of products in stock.
        columns:
          - name: productid
            description: Foreign key to the product table.
            tests:
              - not_null

          - name: locationid
            description: Foreign key to the location table.
            tests:
              - not_null

          - name: quantity
            description: Quantity of the product in stock.
            tests:
              - not_null

      - name: salesperson
        description: General salesperson information.
        columns:
          - name: businessentityid
            description: Primary key of the salesperson table.
            tests:
              - unique
              - not_null

      - name: salesorderdetail
        description: Individual products associated with a specific sales order. See SalesOrderHeader.
        columns:
          - name: salesorderid
            description: Primary key for each sales order detail record.
            tests:
              - not_null
          - name: salesorderdetailid
            description: Unique identifier for each sales order detail.
            tests:
              - unique
              - not_null

      - name: salesorderheader
        description: General sales order information.
        columns:
          - name: salesorderid
            description: Primary key for each sales order.
            tests:
              - unique
              - not_null

      - name: salesorderheadersalesreason
        description: Cross-reference table mapping sales orders to sales reason codes.
        columns:
          - name: "salesorderid || '-' || salesreasonid"
            description: Primary key for sales order reasons.
            tests:
              - unique
              - not_null

      - name: salesreason
        description: Reasons for each purchase.
        columns:
          - name: salesreasonid
            description: Primary key for sales reason table.
            tests:
              - unique
              - not_null

      - name: stateprovince
        description: State and province lookup table.
        columns:
          - name: stateprovinceid
            description: ISO standard code for states and provinces.
            tests:
              - unique
              - not_null

      - name: store
        description: Customers (resellers) of AdventureWorks products.
        columns:
          - name: businessentityid
            description: Primary key for store tables.
            tests:
              - unique
              - not_null
